
http:
  # ROUTERS
  routers:
    # -------------------- ROUTER - DASHBOARD HTTPS --------------------
    dashboardssl:
      rule: Host(`tradash.MY_SUB_DOMAIN.com`)
      service: api@internal
      tls: 
        certResolver: "myresolver"
      middlewares:
        - dash-auth



    # -------------------- ROUTER - NOCO HTTP --------------------
    appnocohttp:
      entryPoints:
        - web
      service: svc-app-noco
      rule: (Host(`noco.MY_SUB_DOMAIN.com`) || (Host(`MY_DOMAIN.com`) && PathPrefix(`/noco/`))) 
      # use middleware
      middlewares:
        - prefix-app-noco

    # -------------------- ROUTER - NOCO HTTPS --------------------
    appnocohttps:
      entryPoints:
        - websecure
      service: svc-app-noco
      rule: (Host(`noco.MY_SUB_DOMAIN.com`) || (Host(`MY_DOMAIN.com`) && PathPrefix(`/noco/`))) 
      tls: 
        certResolver: "myresolver"      
      # use middleware
      middlewares:
        - prefix-app-noco



    # -------------------- ROUTER - CDN MINIO HTTP --------------------
    appcdnhttp:
      entryPoints:
        - web
      service: svc-app-cdn
      rule: (Host(`cdn.MY_SUB_DOMAIN.com`) || (Host(`MY_DOMAIN.com`) && PathPrefix(`/cdn/`)))
      # use middleware
      middlewares:
        - prefix-app-cdn

    # -------------------- ROUTER - CDN MINIO HTTPS --------------------
    appcdnhttps:
      entryPoints:
        - websecure
      service: svc-app-cdn
      rule: (Host(`cdn.MY_SUB_DOMAIN.com`) || (Host(`MY_DOMAIN.com`) && PathPrefix(`/cdn/`)))
      tls: 
        certResolver: "myresolver"
      # use middleware
      middlewares:
        - prefix-app-cdn



    # -------------------- ROUTER - FRONT HTTP --------------------
    appfronthttp:
      entryPoints:
        - web
      service: svc-app-front
      rule: Host(`MY_DOMAIN.com`)

    # -------------------- ROUTER - FRONT HTTPS --------------------
    appfronthttps:
      entryPoints:
        - websecure
      service: svc-app-front
      rule: Host(`MY_DOMAIN.com`)
      tls: 
        certResolver: "myresolver"


    
    # -------------------- ROUTER - API HTTP --------------------
    webapihttp:
      entryPoints:
        - web
      service: svc-app-api
      rule: (Host(`api.MY_SUB_DOMAIN.com`)) || (Host(`MY_DOMAIN.com`) && PathPrefix(`/api/`))
      # use middleware
      middlewares:
        - prefix-app-api

    # -------------------- ROUTER - API HTTPS --------------------
    webapihttps:
      entryPoints:
        - websecure
      service: svc-app-api
      rule: (Host(`api.MY_SUB_DOMAIN.com`)) || (Host(`MY_DOMAIN.com`) && PathPrefix(`/api/`))
      tls: 
        certResolver: "myresolver"
      # use middleware
      middlewares:
        - prefix-app-api



  # SERVICES
  services:    
    # -------------------- SERVICE - NOCO --------------------
    svc-app-noco:
      loadBalancer:
        servers:
          - url: http://SERVICENOCO:PORT
        passHostHeader: true

    # -------------------- SERVICE - CDN MINIO --------------------
    svc-app-cdn:
      loadBalancer:
        servers:
          - url: http://SERVICECDN:PORT
        passHostHeader: true

    # -------------------- SERVICE - FRONT --------------------
    svc-app-front:
      loadBalancer:
        servers:
          - url: http://SERVICEFRONT:PORT
        passHostHeader: true
        
    # -------------------- SERVICE - API --------------------
    svc-app-api:
      loadBalancer:
        servers:
          - url: http://SERVICEAPI:PORT
        passHostHeader: true



  # MIDDLEWARES
  middlewares:

    dash-auth:
      basicAuth:
        users:
          - "test:$apr1$xa0172tu$AfbPBbUq.o7cUch0gn3We/"

    prefix-app-noco:
      stripPrefix:
        prefixes:
          - "/noco/"
        forceSlash: true
    
    prefix-app-cdn:
      stripPrefix:
        prefixes:
          - "/cdn/"
        forceSlash: true
    
    prefix-app-api:
      stripPrefix:
        prefixes:
          - "/api/"
        forceSlash: true
