# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.MY_DOMAIN.com`)"
  file:
    directory: /etc/traefik/dynamic/
    watch: true


# --------------- ENTRYPOINTS ---------------
entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
  
  metrics:
    address: ":8082"



# --------------- API ---------------
api:
  dashboard: true
  insecure: false


# --------------- METRICS ---------------
metrics:
  prometheus:
    entryPoint: metrics


# --------------- TLS ---------------
certificatesResolvers:
  myresolver:
    acme:
      email: support@MY_DOMAIN.com
      storage: /home/support/acme.json
      # HTTP Challenge
      httpChallenge:
        # used during the challenge
        entryPoint: web


# --------------- LOG ---------------
accessLog:
  filePath: "/home/support/access.log"
  format: json
  bufferingSize: 100
#  File Support
#  filePath: "/home/support/access.log"
#  format: json
#  bufferingSize: 100
